# Generated by Django 4.2.2 on 2023-07-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Concerts', 'Concerts'), ('Classes & Workshops', 'Classes & Workshops'), ('Corporate Events', 'Corporate Events'), ('Festivals & Fairs', 'Festivals & Fairs')], max_length=200, null=True)),
                ('place_of_event', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_of_organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.organizer')),
            ],
        ),
    ]
