# Generated by Django 4.2.2 on 2023-07-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_eventregistration_event_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.event'),
        ),
    ]
