# Generated by Django 4.2.2 on 2023-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_client_user_alter_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
